import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://gavelling.com',             lastModified: new Date(), changeFrequency: 'weekly',  priority: 1   },
    { url: 'https://gavelling.com/about',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/conferences',  lastModified: new Date(), changeFrequency: 'weekly',  priority: 0.8 },
    { url: 'https://gavelling.com/contact',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://gavelling.com/features',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://gavelling.com/pricing',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/resources',    lastModified: new Date(), changeFrequency: 'weekly',  priority: 0.8 },
    { url: 'https://gavelling.com/blog',         lastModified: new Date(), changeFrequency: 'weekly',  priority: 0.9 },
    { url: 'https://gavelling.com/blog/how-to-run-mun-committee',    lastModified: new Date('2026-06-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/best-mun-software-2026',      lastModified: new Date('2026-06-01'), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://gavelling.com/blog/general-speakers-list-guide',  lastModified: new Date('2026-06-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-motions-explained',        lastModified: new Date('2026-06-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/how-to-chair-first-mun',       lastModified: new Date('2026-06-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/how-to-run-moderated-caucus',  lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/unmoderated-caucus-guide',     lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-voting-procedures',        lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-delegate-tips',            lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-position-paper-guide',     lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-resolution-writing',       lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-rules-of-procedure',       lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-security-council-guide',   lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-crisis-committee-guide',   lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/free-mun-tools',               lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://gavelling.com/blog/mun-conference-preparation',   lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-public-speaking-tips',     lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-opening-speech',           lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-working-paper-guide',      lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-amendment-guide',          lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-right-of-reply',           lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://gavelling.com/blog/tour-de-table-mun',            lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-director-guide',           lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-chair-script',             lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-bloc-building',            lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-awards-guide',             lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-conference-planning',      lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-technology-guide',         lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-online-committees',        lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-faculty-advisor-guide',    lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://gavelling.com/blog/mun-points-of-order',          lastModified: new Date('2026-06-07'), changeFrequency: 'monthly', priority: 0.8 },
  ];
}
