/**
 * CreditCoin — the credit token.
 *
 * Owner, 23 Sep 2026: the gold Gavelling token drawn for the pre-registrant
 * emails (gavel and laurel struck in forest on gold) is THE credit image, on
 * the site as well as in email. The artwork is one file, `/credit-token.webp`
 * (PNG fallback `/credit-token.png`, 256px, no outer shadow so it sits cleanly
 * in the 16px nav chip), generated by `scripts/email-token-art.py`. The email
 * copies live in `public/email/` and in the `email-assets` storage folder.
 *
 * It is a depicted object, like a flag, so it keeps its gold and green on any
 * background and takes no dark-mode variant.
 *
 * `title` makes it a labelled graphic for screen readers; omit it (the default)
 * and it is decorative and hidden, which is right beside a visible number.
 */
export function CreditCoin({
  size = 16,
  title,
  className,
  style,
}: {
  size?: number;
  title?: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <picture style={{ flexShrink: 0, display: 'block', lineHeight: 0, ...style }} className={className}>
      <source srcSet="/credit-token.webp" type="image/webp" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/credit-token.png"
        width={size}
        height={size}
        alt={title ?? ''}
        aria-hidden={title ? undefined : true}
        draggable={false}
        decoding="async"
        style={{ width: size, height: size, objectFit: 'contain', display: 'block' }}
      />
    </picture>
  );
}
